name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    services:
      redis:
        image: redis
        ports:
          - 6379:6379

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip wheel setuptools
        python -m pip install pytest pytest-cov pytest-asyncio coverage
        python -m pip install -e ".[test]"
        
    - name: Verify environment
      run: |
        echo "Current PATH: $PATH"
        echo "Python location: $(which python)"
        echo "Python version: $(python --version)"
        echo "Pip location: $(which pip)"
        echo "Pip version: $(pip --version)"
        echo "Installed packages:"
        python -m pip list
        echo "Testing pytest installation:"
        python -m pytest --version
        
    - name: Run tests
      env:
        PYTHONPATH: ${{ github.workspace }}
      run: |
        python -m pytest tests/ --cov=quickcache --cov-report=xml
        
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: false